# Generated by Django 5.0.14 on 2025-12-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_feedbacks",
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_projects",
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "-posted_date"], name="projects_pr_status_15b69d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category"], name="projects_pr_categor_220446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["status", "-request_date"], name="projects_jo_status_fa8fc3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="joinrequest",
            unique_together={("project", "student")},
        ),
    ]
