# Generated by Django 6.0 on 2025-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="faculty",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="faculty",
            name="office_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="faculty",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="faculty",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
